/**********************************************************************************************************************
 * \file GPIO_LED_Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"

/*********************************************************************************************************************/
/*-----------------------------------------------------Macros--------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED     &MODULE_P13,3   /* Port pin for the LED     */
#define BUTTON  &MODULE_P14,4   /* Port pin for the button  */
#define GROUND  &MODULE_P14,5

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Function to configure the port pins for the push button and the LED */
void init_GPIOs(void)
{
    /* Setup the port pin connected to the LED to general output mode push-pull. This function can be used
     * to initialize any port pin by specifying the port number, pin number and port pin mode.
     */
    IfxPort_setPinMode(LED, IfxPort_Mode_outputPushPullGeneral);

    /* Setup the port pin connected to the push button to input mode. This function can be used to initialize any
     * port to input mode by just specifying the port number as illustrated.
     */
    IfxPort_setPinMode(BUTTON, IfxPort_Mode_inputPullUp);

    /* In order to force the push button pin with the neighboring pin to low level when connecting these two pins
     * together, this neighboring pin drives low level and is set to push-pull mode
     */
    IfxPort_setPinState(GROUND, IfxPort_State_low);
    IfxPort_setPinMode(GROUND, IfxPort_Mode_outputPushPullGeneral);
    /*
     IfxPort_setPinModeOutput(LED, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);等价于
     IfxPort_setPinMode(LED, IfxPort_Mode_outputPushPullGeneral);
    // 输入模式
    IfxPort_Mode_inputNoPullDevice     = 0x00   // 浮空输入
    IfxPort_Mode_inputPullDown         = 0x08   // 下拉输入
    IfxPort_Mode_inputPullUp           = 0x10   // 上拉输入

    // 推挽输出 (Push-Pull)
    IfxPort_Mode_outputPushPullGeneral = 0x80   // 通用推挽 (GPIO)
    IfxPort_Mode_outputPushPullAlt1    = 0x88   // 复用功能1 (如 UART_TX)
    IfxPort_Mode_outputPushPullAlt2    = 0x90   // 复用功能2 (如 SPI_CLK)
    IfxPort_Mode_outputPushPullAlt3    = 0x98   // 复用功能3
    ...Alt4 ~ Alt7                              // 复用功能4~7

    // 开漏输出 (Open-Drain)
    IfxPort_Mode_outputOpenDrainGeneral = 0xC0  // 通用开漏
    IfxPort_Mode_outputOpenDrainAlt1    = 0xC8  // 复用开漏1 (如 I2C_SDA)
    ...Alt2 ~ Alt7                              // 复用开漏2~7
    每个引脚可以连接到不同的外设（UART/SPI/CAN/GTM...），具体哪个 Alt 对应哪个外设，需要查 数据手册的引脚复用表
    */
}

/* Depending on the the state of the "BUTTON" port pin, the LED is turned on or off */
void control_LED(void)
{
    /* With the routine getPinState() the value of a particular pin can be retrieved. This
     * function can be used to retrieve any port state by just specifying the port number
     * as illustrated.
     */
    if(IfxPort_getPinState(BUTTON) == 0)
    {
        /* With the routine setPinState() the state of the port can be set to drive either
         * LOW or HIGH. This function can be used to retrieve any port state by just
         * specifying the port number as illustrated.
         */
        IfxPort_setPinState(LED, IfxPort_State_low);
    }
    else
    {
        IfxPort_setPinState(LED, IfxPort_State_high);
    }
}
